
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 11 17:03:40 CST 2018
//----------------------------------------------------

package minicsharp;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READLINE = 51;
  public static final int MULT = 4;
  public static final int BRACKETS = 28;
  public static final int INTEGER = 55;
  public static final int DOUBLE = 31;
  public static final int GREATER = 9;
  public static final int INTERFACE = 36;
  public static final int PAR_LEFT = 22;
  public static final int INT = 30;
  public static final int FOR = 41;
  public static final int MINUS = 7;
  public static final int BRACKET_RIGHT = 25;
  public static final int BRACKET_LEFT = 24;
  public static final int SUBSTRACTION = 3;
  public static final int NOT = 16;
  public static final int AND = 14;
  public static final int READINTEGER = 50;
  public static final int PAR_RIGHT = 23;
  public static final int OR = 15;
  public static final int BOOL = 33;
  public static final int DOUBLECONSTANT = 60;
  public static final int CLASS = 35;
  public static final int DIV = 5;
  public static final int MINUS_EQUAL = 8;
  public static final int NEWARRAY = 48;
  public static final int DIFFERENT = 13;
  public static final int BOOLCONSTANT = 61;
  public static final int IF = 43;
  public static final int ASSIGN = 11;
  public static final int GETBYTE = 57;
  public static final int THIS = 38;
  public static final int INTCONSTANT = 59;
  public static final int SETBYTE = 58;
  public static final int EOF = 0;
  public static final int RETURN = 45;
  public static final int EQUAL = 12;
  public static final int TRUE = 53;
  public static final int GREATER_EQUAL = 10;
  public static final int STRINGCONSTANT = 62;
  public static final int NEW = 47;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int ADD = 2;
  public static final int SEMI_COLON = 17;
  public static final int NULL = 37;
  public static final int MOD = 6;
  public static final int SB_RIGHT = 21;
  public static final int IDENT = 56;
  public static final int BREAK = 46;
  public static final int VOID = 29;
  public static final int PARENTHESIS = 27;
  public static final int ELSE = 44;
  public static final int SBCHETES = 26;
  public static final int POINT = 19;
  public static final int SB_LEFT = 20;
  public static final int WHILE = 42;
  public static final int EXTENDS = 39;
  public static final int HEXADECIMAL = 32;
  public static final int STRING = 34;
  public static final int MALLOC = 52;
  public static final int FALSE = 54;
  public static final int IMPLEMENTS = 40;
  public static final int PRINT = 49;
}

