/* The following code was generated by JFlex 1.6.1 */

package minicsharp;
import static minicsharp.Token.*;
import java_cup.runtime.*;
import java_cup.sym;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>/home/diego/Desktop/MiniCSharp-master (copy)/MiniCSharp/src/minicsharp/Lexer.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\16\1\6\1\5\1\0\1\6\1\4\16\16\4\0\1\6\1\65"+
    "\1\100\1\0\1\15\1\61\1\66\1\0\1\74\1\75\1\10\1\57"+
    "\1\3\1\60\1\71\1\7\1\11\11\2\1\0\1\70\1\62\1\63"+
    "\1\64\2\0\1\25\1\40\2\13\1\30\1\24\1\37\4\15\1\26"+
    "\1\15\1\56\3\15\1\35\1\27\1\34\1\36\2\15\1\14\2\15"+
    "\1\72\1\0\1\73\1\0\1\15\1\0\1\20\1\1\1\50\1\45"+
    "\1\23\1\17\1\47\1\51\1\44\1\15\1\55\1\21\1\52\1\46"+
    "\1\43\1\53\1\15\1\32\1\22\1\31\1\33\1\42\1\54\1\12"+
    "\1\41\1\15\1\76\1\67\1\77\1\0\41\16\2\0\4\15\4\0"+
    "\1\15\2\0\1\16\7\0\1\15\4\0\1\15\5\0\27\15\1\0"+
    "\37\15\1\0\u01ca\15\4\0\14\15\16\0\5\15\7\0\1\15\1\0"+
    "\1\15\21\0\160\16\5\15\1\0\2\15\2\0\4\15\10\0\1\15"+
    "\1\0\3\15\1\0\1\15\1\0\24\15\1\0\123\15\1\0\213\15"+
    "\1\0\5\16\2\0\236\15\11\0\46\15\2\0\1\15\7\0\47\15"+
    "\7\0\1\15\1\0\55\16\1\0\1\16\1\0\2\16\1\0\2\16"+
    "\1\0\1\16\10\0\33\15\5\0\3\15\15\0\5\16\6\0\1\15"+
    "\4\0\13\16\5\0\53\15\37\16\4\0\2\15\1\16\143\15\1\0"+
    "\1\15\10\16\1\0\6\16\2\15\2\16\1\0\4\16\2\15\12\16"+
    "\3\15\2\0\1\15\17\0\1\16\1\15\1\16\36\15\33\16\2\0"+
    "\131\15\13\16\1\15\16\0\12\16\41\15\11\16\2\15\4\0\1\15"+
    "\5\0\26\15\4\16\1\15\11\16\1\15\3\16\1\15\5\16\22\0"+
    "\31\15\3\16\104\0\1\15\1\0\13\15\67\0\33\16\1\0\4\16"+
    "\66\15\3\16\1\15\22\16\1\15\7\16\12\15\2\16\2\0\12\16"+
    "\1\0\7\15\1\0\7\15\1\0\3\16\1\0\10\15\2\0\2\15"+
    "\2\0\26\15\1\0\7\15\1\0\1\15\3\0\4\15\2\0\1\16"+
    "\1\15\7\16\2\0\2\16\2\0\3\16\1\15\10\0\1\16\4\0"+
    "\2\15\1\0\3\15\2\16\2\0\12\16\4\15\7\0\1\15\5\0"+
    "\3\16\1\0\6\15\4\0\2\15\2\0\26\15\1\0\7\15\1\0"+
    "\2\15\1\0\2\15\1\0\2\15\2\0\1\16\1\0\5\16\4\0"+
    "\2\16\2\0\3\16\3\0\1\16\7\0\4\15\1\0\1\15\7\0"+
    "\14\16\3\15\1\16\13\0\3\16\1\0\11\15\1\0\3\15\1\0"+
    "\26\15\1\0\7\15\1\0\2\15\1\0\5\15\2\0\1\16\1\15"+
    "\10\16\1\0\3\16\1\0\3\16\2\0\1\15\17\0\2\15\2\16"+
    "\2\0\12\16\1\0\1\15\17\0\3\16\1\0\10\15\2\0\2\15"+
    "\2\0\26\15\1\0\7\15\1\0\2\15\1\0\5\15\2\0\1\16"+
    "\1\15\7\16\2\0\2\16\2\0\3\16\10\0\2\16\4\0\2\15"+
    "\1\0\3\15\2\16\2\0\12\16\1\0\1\15\20\0\1\16\1\15"+
    "\1\0\6\15\3\0\3\15\1\0\4\15\3\0\2\15\1\0\1\15"+
    "\1\0\2\15\3\0\2\15\3\0\3\15\3\0\14\15\4\0\5\16"+
    "\3\0\3\16\1\0\4\16\2\0\1\15\6\0\1\16\16\0\12\16"+
    "\11\0\1\15\7\0\3\16\1\0\10\15\1\0\3\15\1\0\27\15"+
    "\1\0\12\15\1\0\5\15\3\0\1\15\7\16\1\0\3\16\1\0"+
    "\4\16\7\0\2\16\1\0\2\15\6\0\2\15\2\16\2\0\12\16"+
    "\22\0\2\16\1\0\10\15\1\0\3\15\1\0\27\15\1\0\12\15"+
    "\1\0\5\15\2\0\1\16\1\15\7\16\1\0\3\16\1\0\4\16"+
    "\7\0\2\16\7\0\1\15\1\0\2\15\2\16\2\0\12\16\1\0"+
    "\2\15\17\0\2\16\1\0\10\15\1\0\3\15\1\0\51\15\2\0"+
    "\1\15\7\16\1\0\3\16\1\0\4\16\1\15\10\0\1\16\10\0"+
    "\2\15\2\16\2\0\12\16\12\0\6\15\2\0\2\16\1\0\22\15"+
    "\3\0\30\15\1\0\11\15\1\0\1\15\2\0\7\15\3\0\1\16"+
    "\4\0\6\16\1\0\1\16\1\0\10\16\22\0\2\16\15\0\60\15"+
    "\1\16\2\15\7\16\4\0\10\15\10\16\1\0\12\16\47\0\2\15"+
    "\1\0\1\15\2\0\2\15\1\0\1\15\2\0\1\15\6\0\4\15"+
    "\1\0\7\15\1\0\3\15\1\0\1\15\1\0\1\15\2\0\2\15"+
    "\1\0\4\15\1\16\2\15\6\16\1\0\2\16\1\15\2\0\5\15"+
    "\1\0\1\15\1\0\6\16\2\0\12\16\2\0\4\15\40\0\1\15"+
    "\27\0\2\16\6\0\12\16\13\0\1\16\1\0\1\16\1\0\1\16"+
    "\4\0\2\16\10\15\1\0\44\15\4\0\24\16\1\0\2\16\5\15"+
    "\13\16\1\0\44\16\11\0\1\16\71\0\53\15\24\16\1\15\12\16"+
    "\6\0\6\15\4\16\4\15\3\16\1\15\3\16\2\15\7\16\3\15"+
    "\4\16\15\15\14\16\1\15\17\16\2\0\46\15\1\0\1\15\5\0"+
    "\1\15\2\0\53\15\1\0\u014d\15\1\0\4\15\2\0\7\15\1\0"+
    "\1\15\1\0\4\15\2\0\51\15\1\0\4\15\2\0\41\15\1\0"+
    "\4\15\2\0\7\15\1\0\1\15\1\0\4\15\2\0\17\15\1\0"+
    "\71\15\1\0\4\15\2\0\103\15\2\0\3\16\40\0\20\15\20\0"+
    "\125\15\14\0\u026c\15\2\0\21\15\1\0\32\15\5\0\113\15\3\0"+
    "\3\15\17\0\15\15\1\0\4\15\3\16\13\0\22\15\3\16\13\0"+
    "\22\15\2\16\14\0\15\15\1\0\3\15\1\0\2\16\14\0\64\15"+
    "\40\16\3\0\1\15\3\0\2\15\1\16\2\0\12\16\41\0\3\16"+
    "\2\0\12\16\6\0\130\15\10\0\51\15\1\16\1\15\5\0\106\15"+
    "\12\0\35\15\3\0\14\16\4\0\14\16\12\0\12\16\36\15\2\0"+
    "\5\15\13\0\54\15\4\0\21\16\7\15\2\16\6\0\12\16\46\0"+
    "\27\15\5\16\4\0\65\15\12\16\1\0\35\16\2\0\13\16\6\0"+
    "\12\16\15\0\1\15\130\0\5\16\57\15\21\16\7\15\4\0\12\16"+
    "\21\0\11\16\14\0\3\16\36\15\15\16\2\15\12\16\54\15\16\16"+
    "\14\0\44\15\24\16\10\0\12\16\3\0\3\15\12\16\44\15\122\0"+
    "\3\16\1\0\25\16\4\15\1\16\4\15\3\16\2\15\11\0\300\15"+
    "\47\16\25\0\4\16\u0116\15\2\0\6\15\2\0\46\15\2\0\6\15"+
    "\2\0\10\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0\37\15"+
    "\2\0\65\15\1\0\7\15\1\0\1\15\3\0\3\15\1\0\7\15"+
    "\3\0\4\15\2\0\6\15\4\0\15\15\5\0\3\15\1\0\7\15"+
    "\16\0\5\16\32\0\5\16\20\0\2\15\23\0\1\15\13\0\5\16"+
    "\5\0\6\16\1\0\1\15\15\0\1\15\20\0\15\15\3\0\33\15"+
    "\25\0\15\16\4\0\1\16\3\0\14\16\21\0\1\15\4\0\1\15"+
    "\2\0\12\15\1\0\1\15\3\0\5\15\6\0\1\15\1\0\1\15"+
    "\1\0\1\15\1\0\4\15\1\0\13\15\2\0\4\15\5\0\5\15"+
    "\4\0\1\15\21\0\51\15\u0a77\0\57\15\1\0\57\15\1\0\205\15"+
    "\6\0\4\15\3\16\2\15\14\0\46\15\1\0\1\15\5\0\1\15"+
    "\2\0\70\15\7\0\1\15\17\0\1\16\27\15\11\0\7\15\1\0"+
    "\7\15\1\0\7\15\1\0\7\15\1\0\7\15\1\0\7\15\1\0"+
    "\7\15\1\0\7\15\1\0\40\16\57\0\1\15\u01d5\0\3\15\31\0"+
    "\11\15\6\16\1\0\5\15\2\0\5\15\4\0\126\15\2\0\2\16"+
    "\2\0\3\15\1\0\132\15\1\0\4\15\5\0\51\15\3\0\136\15"+
    "\21\0\33\15\65\0\20\15\u0200\0\u19b6\15\112\0\u51cd\15\63\0\u048d\15"+
    "\103\0\56\15\2\0\u010d\15\3\0\20\15\12\16\2\15\24\0\57\15"+
    "\1\16\4\0\12\16\1\0\31\15\7\0\1\16\120\15\2\16\45\0"+
    "\11\15\2\0\147\15\2\0\4\15\1\0\4\15\14\0\13\15\115\0"+
    "\12\15\1\16\3\15\1\16\4\15\1\16\27\15\5\16\20\0\1\15"+
    "\7\0\64\15\14\0\2\16\62\15\21\16\13\0\12\16\6\0\22\16"+
    "\6\15\3\0\1\15\4\0\12\16\34\15\10\16\2\0\27\15\15\16"+
    "\14\0\35\15\3\0\4\16\57\15\16\16\16\0\1\15\12\16\46\0"+
    "\51\15\16\16\11\0\3\15\1\16\10\15\2\16\2\0\12\16\6\0"+
    "\27\15\3\0\1\15\1\16\4\0\60\15\1\16\1\15\3\16\2\15"+
    "\2\16\5\15\2\16\1\15\1\16\1\15\30\0\3\15\2\0\13\15"+
    "\5\16\2\0\3\15\2\16\12\0\6\15\2\0\6\15\2\0\6\15"+
    "\11\0\7\15\1\0\7\15\221\0\43\15\10\16\1\0\2\16\2\0"+
    "\12\16\6\0\u2ba4\15\14\0\27\15\4\0\61\15\u2104\0\u016e\15\2\0"+
    "\152\15\46\0\7\15\14\0\5\15\5\0\1\15\1\16\12\15\1\0"+
    "\15\15\1\0\5\15\1\0\1\15\1\0\2\15\1\0\2\15\1\0"+
    "\154\15\41\0\u016b\15\22\0\100\15\2\0\66\15\50\0\15\15\3\0"+
    "\20\16\20\0\7\16\14\0\2\15\30\0\3\15\31\0\1\15\6\0"+
    "\5\15\1\0\207\15\2\0\1\16\4\0\1\15\13\0\12\16\7\0"+
    "\32\15\4\0\1\15\1\0\32\15\13\0\131\15\3\0\6\15\2\0"+
    "\6\15\2\0\6\15\2\0\3\15\3\0\2\15\3\0\2\15\22\0"+
    "\3\16\4\0\14\15\1\0\32\15\1\0\23\15\1\0\2\15\1\0"+
    "\17\15\2\0\16\15\42\0\173\15\105\0\65\15\210\0\1\16\202\0"+
    "\35\15\3\0\61\15\57\0\37\15\21\0\33\15\65\0\36\15\2\0"+
    "\44\15\4\0\10\15\1\0\5\15\52\0\236\15\2\0\12\16\u0356\0"+
    "\6\15\2\0\1\15\1\0\54\15\1\0\2\15\3\0\1\15\2\0"+
    "\27\15\252\0\26\15\12\0\32\15\106\0\70\15\6\0\2\15\100\0"+
    "\1\15\3\16\1\0\2\16\5\0\4\16\4\15\1\0\3\15\1\0"+
    "\33\15\4\0\3\16\4\0\1\16\40\0\35\15\203\0\66\15\12\0"+
    "\26\15\12\0\23\15\215\0\111\15\u03b7\0\3\16\65\15\17\16\37\0"+
    "\12\16\20\0\3\16\55\15\13\16\2\0\1\16\22\0\31\15\7\0"+
    "\12\16\6\0\3\16\44\15\16\16\1\0\12\16\100\0\3\16\60\15"+
    "\16\16\4\15\13\0\12\16\u04a6\0\53\15\15\16\10\0\12\16\u0936\0"+
    "\u036f\15\221\0\143\15\u0b9d\0\u042f\15\u33d1\0\u0239\15\u04c7\0\105\15\13\0"+
    "\1\15\56\16\20\0\4\16\15\15\u4060\0\2\15\u2163\0\5\16\3\0"+
    "\26\16\2\0\7\16\36\0\4\16\224\0\3\16\u01bb\0\125\15\1\0"+
    "\107\15\1\0\2\15\2\0\1\15\2\0\2\15\2\0\4\15\1\0"+
    "\14\15\1\0\1\15\1\0\7\15\1\0\101\15\1\0\4\15\2\0"+
    "\10\15\1\0\7\15\1\0\34\15\1\0\4\15\1\0\5\15\1\0"+
    "\1\15\3\0\7\15\1\0\u0154\15\2\0\31\15\1\0\31\15\1\0"+
    "\37\15\1\0\31\15\1\0\37\15\1\0\31\15\1\0\37\15\1\0"+
    "\31\15\1\0\37\15\1\0\31\15\1\0\10\15\2\0\62\16\u1600\0"+
    "\4\15\1\0\33\15\1\0\2\15\1\0\1\15\2\0\1\15\1\0"+
    "\12\15\1\0\4\15\1\0\1\15\1\0\1\15\6\0\1\15\4\0"+
    "\1\15\1\0\1\15\1\0\1\15\1\0\3\15\1\0\2\15\1\0"+
    "\1\15\2\0\1\15\1\0\1\15\1\0\1\15\1\0\1\15\1\0"+
    "\1\15\1\0\2\15\1\0\1\15\2\0\4\15\1\0\7\15\1\0"+
    "\4\15\1\0\4\15\1\0\1\15\1\0\12\15\1\0\21\15\5\0"+
    "\3\15\1\0\5\15\1\0\21\15\u1144\0\ua6d7\15\51\0\u1035\15\13\0"+
    "\336\15\u3fe2\0\u021e\15\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\u05ee\0"+
    "\1\16\36\0\140\16\200\0\360\16\uffff\0\uffff\0\ufe12\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\1\1\4\1\5\1\6\1\5"+
    "\1\7\1\10\1\1\21\3\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\2\2\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\2\2\3\1\30\1\5"+
    "\2\0\15\3\1\31\7\3\1\0\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\0\2\3"+
    "\3\0\1\1\1\3\1\43\13\3\1\44\5\3\1\45"+
    "\1\46\1\3\1\47\1\30\2\0\1\5\3\3\1\50"+
    "\2\3\1\51\1\52\2\3\1\53\3\3\1\54\3\3"+
    "\1\55\1\56\10\3\1\57\1\60\1\3\1\46\2\3"+
    "\1\61\3\3\1\62\1\3\1\63\1\64\1\65\5\3"+
    "\1\66\1\67\1\3\1\70";

  private static int [] zzUnpackAction() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\101\0\202\0\303\0\101\0\u0104\0\101\0\101"+
    "\0\u0145\0\101\0\u0186\0\u01c7\0\u0208\0\u0249\0\u028a\0\u02cb"+
    "\0\u030c\0\u034d\0\u038e\0\u03cf\0\u0410\0\u0451\0\u0492\0\u04d3"+
    "\0\u0514\0\u0555\0\u0596\0\u05d7\0\u0618\0\u0618\0\101\0\u0659"+
    "\0\u069a\0\u06db\0\u071c\0\u075d\0\u079e\0\101\0\101\0\u07df"+
    "\0\101\0\u0820\0\101\0\u0861\0\101\0\u08a2\0\u08e3\0\u0924"+
    "\0\u0965\0\u09a6\0\u09e7\0\u0a28\0\u0a69\0\u0aaa\0\u0aeb\0\u0b2c"+
    "\0\u0b6d\0\u0bae\0\u0bef\0\u0c30\0\u0c71\0\u0cb2\0\u0cf3\0\u0d34"+
    "\0\u0d75\0\u01c7\0\u0db6\0\u0df7\0\u0e38\0\u0e79\0\u0eba\0\u0efb"+
    "\0\u0f3c\0\u0f7d\0\101\0\101\0\101\0\101\0\101\0\101"+
    "\0\101\0\101\0\101\0\u0fbe\0\u0fff\0\u1040\0\u1081\0\u10c2"+
    "\0\u1103\0\u0a28\0\u1144\0\u01c7\0\u1185\0\u11c6\0\u1207\0\u1248"+
    "\0\u1289\0\u12ca\0\u130b\0\u134c\0\u138d\0\u13ce\0\u140f\0\u1450"+
    "\0\u1491\0\u14d2\0\u1513\0\u1554\0\u1595\0\u15d6\0\u0fbe\0\u1617"+
    "\0\u01c7\0\u1658\0\u1658\0\u1699\0\u10c2\0\u16da\0\u171b\0\u175c"+
    "\0\u01c7\0\u179d\0\u17de\0\u01c7\0\u01c7\0\u181f\0\u1860\0\u01c7"+
    "\0\u18a1\0\u18e2\0\u1923\0\u01c7\0\u1964\0\u19a5\0\u19e6\0\u01c7"+
    "\0\u01c7\0\u1a27\0\u1a68\0\u1aa9\0\u1aea\0\u1b2b\0\u1b6c\0\u1bad"+
    "\0\u1bee\0\u01c7\0\u01c7\0\u1c2f\0\u01c7\0\u1c70\0\u1cb1\0\u01c7"+
    "\0\u1cf2\0\u1d33\0\u1d74\0\u01c7\0\u1db5\0\u01c7\0\u01c7\0\u01c7"+
    "\0\u1df6\0\u1e37\0\u1e78\0\u1eb9\0\u1efa\0\u01c7\0\u01c7\0\u1f3b"+
    "\0\u01c7";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\4\14\1\2\1\15\2\14\1\16\1\17"+
    "\1\20\2\14\1\21\1\14\1\22\1\23\1\14\1\24"+
    "\2\14\1\25\2\14\1\26\1\14\1\27\1\30\1\31"+
    "\1\14\1\32\3\14\1\33\1\14\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\102\0\2\14\6\0\21\14\1\57\10\14\1\60\13\14"+
    "\24\0\1\4\6\0\1\4\57\0\1\61\14\0\1\10"+
    "\102\0\1\62\1\63\72\0\1\4\6\0\1\4\1\64"+
    "\1\0\1\64\54\0\1\61\10\0\2\14\6\0\46\14"+
    "\23\0\2\14\6\0\7\14\1\65\22\14\1\66\13\14"+
    "\23\0\2\14\6\0\20\14\1\67\25\14\23\0\2\14"+
    "\6\0\1\14\1\70\6\14\1\71\35\14\23\0\2\14"+
    "\6\0\14\14\1\72\31\14\23\0\2\14\6\0\12\14"+
    "\1\73\33\14\23\0\2\14\6\0\21\14\1\74\16\14"+
    "\1\75\5\14\23\0\2\14\6\0\12\14\1\76\33\14"+
    "\23\0\2\14\6\0\24\14\1\77\21\14\23\0\2\14"+
    "\6\0\12\14\1\100\33\14\23\0\2\14\6\0\32\14"+
    "\1\101\13\14\23\0\2\14\6\0\6\14\1\102\26\14"+
    "\1\103\3\14\1\104\4\14\23\0\2\14\6\0\32\14"+
    "\1\105\13\14\23\0\2\14\6\0\22\14\1\106\23\14"+
    "\23\0\2\14\6\0\10\14\1\107\35\14\23\0\2\14"+
    "\6\0\40\14\1\110\5\14\23\0\2\14\6\0\12\14"+
    "\1\111\33\14\24\0\1\112\6\0\1\112\152\0\1\113"+
    "\100\0\1\114\100\0\1\115\100\0\1\116\103\0\1\117"+
    "\101\0\1\120\104\0\1\121\102\0\1\122\102\0\1\123"+
    "\1\0\4\124\2\0\73\124\1\0\2\14\6\0\12\14"+
    "\1\125\33\14\23\0\2\14\6\0\32\14\1\126\13\14"+
    "\24\0\1\61\6\0\1\61\11\0\1\127\4\0\1\127"+
    "\50\0\4\62\1\6\1\0\73\62\10\130\1\131\70\130"+
    "\1\0\2\132\6\0\1\132\1\0\1\132\3\0\2\132"+
    "\2\0\3\132\2\0\1\132\7\0\1\132\4\0\1\132"+
    "\2\0\1\132\31\0\2\14\6\0\10\14\1\133\35\14"+
    "\23\0\2\14\6\0\21\14\1\134\24\14\23\0\2\14"+
    "\6\0\21\14\1\135\24\14\23\0\2\14\6\0\20\14"+
    "\1\136\25\14\23\0\2\14\6\0\11\14\1\137\34\14"+
    "\23\0\2\14\6\0\15\14\1\140\30\14\23\0\2\14"+
    "\6\0\20\14\1\141\25\14\23\0\2\14\6\0\22\14"+
    "\1\142\23\14\23\0\2\14\6\0\33\14\1\143\12\14"+
    "\23\0\2\14\6\0\20\14\1\144\25\14\23\0\2\14"+
    "\6\0\25\14\1\145\20\14\23\0\2\14\6\0\20\14"+
    "\1\146\25\14\23\0\2\14\6\0\33\14\1\147\12\14"+
    "\23\0\2\14\6\0\20\14\1\150\25\14\23\0\2\14"+
    "\6\0\42\14\1\151\3\14\23\0\2\14\6\0\22\14"+
    "\1\152\23\14\23\0\2\14\6\0\10\14\1\153\35\14"+
    "\23\0\2\14\6\0\7\14\1\154\36\14\23\0\2\14"+
    "\6\0\33\14\1\155\12\14\23\0\2\14\6\0\43\14"+
    "\1\156\2\14\24\0\1\112\6\0\1\112\57\0\1\61"+
    "\7\0\4\124\2\0\72\124\1\157\1\0\2\14\6\0"+
    "\7\14\1\160\36\14\23\0\2\14\6\0\10\14\1\161"+
    "\35\14\24\0\1\162\6\0\1\162\45\0\2\163\20\0"+
    "\10\130\1\164\77\130\1\165\1\164\70\130\1\0\2\14"+
    "\6\0\11\14\1\166\34\14\23\0\2\14\6\0\33\14"+
    "\1\167\12\14\23\0\2\14\6\0\12\14\1\170\33\14"+
    "\23\0\2\14\6\0\12\14\1\171\33\14\23\0\2\14"+
    "\6\0\16\14\1\172\27\14\23\0\2\14\6\0\27\14"+
    "\1\173\16\14\23\0\2\14\6\0\12\14\1\174\33\14"+
    "\23\0\2\14\6\0\11\14\1\175\34\14\23\0\2\14"+
    "\6\0\22\14\1\176\23\14\23\0\2\14\6\0\17\14"+
    "\1\174\26\14\23\0\2\14\6\0\27\14\1\177\16\14"+
    "\23\0\2\14\6\0\34\14\1\200\11\14\23\0\2\14"+
    "\6\0\12\14\1\201\33\14\23\0\2\14\6\0\10\14"+
    "\1\202\35\14\23\0\1\203\1\14\6\0\46\14\23\0"+
    "\2\14\6\0\10\14\1\204\35\14\23\0\2\14\6\0"+
    "\11\14\1\205\34\14\23\0\2\14\6\0\10\14\1\206"+
    "\35\14\23\0\2\14\6\0\14\14\1\207\31\14\23\0"+
    "\2\14\6\0\44\14\1\210\1\14\24\0\1\162\6\0"+
    "\1\162\67\0\7\130\1\10\1\164\70\130\1\0\2\14"+
    "\6\0\12\14\1\211\33\14\23\0\2\14\6\0\35\14"+
    "\1\212\10\14\23\0\2\14\6\0\35\14\1\213\10\14"+
    "\23\0\2\14\6\0\17\14\1\211\26\14\23\0\2\14"+
    "\6\0\30\14\1\214\15\14\23\0\2\14\6\0\21\14"+
    "\1\215\24\14\23\0\2\14\6\0\30\14\1\216\15\14"+
    "\23\0\2\14\6\0\21\14\1\217\24\14\23\0\2\14"+
    "\6\0\12\14\1\220\33\14\23\0\2\14\6\0\10\14"+
    "\1\221\35\14\23\0\2\14\6\0\11\14\1\222\34\14"+
    "\23\0\2\14\6\0\12\14\1\223\33\14\23\0\2\14"+
    "\6\0\21\14\1\224\24\14\23\0\2\14\6\0\36\14"+
    "\1\225\7\14\23\0\2\14\6\0\34\14\1\226\11\14"+
    "\23\0\2\14\6\0\20\14\1\227\25\14\23\0\2\14"+
    "\6\0\35\14\1\230\10\14\23\0\2\14\6\0\20\14"+
    "\1\231\25\14\23\0\2\14\6\0\6\14\1\232\37\14"+
    "\23\0\2\14\6\0\41\14\1\233\4\14\23\0\2\14"+
    "\6\0\12\14\1\234\33\14\23\0\2\14\6\0\21\14"+
    "\1\235\24\14\23\0\2\14\6\0\11\14\1\236\34\14"+
    "\23\0\2\14\6\0\12\14\1\237\33\14\23\0\2\14"+
    "\6\0\12\14\1\240\33\14\23\0\2\14\6\0\7\14"+
    "\1\241\36\14\23\0\2\14\6\0\12\14\1\242\33\14"+
    "\23\0\2\14\6\0\7\14\1\243\36\14\23\0\2\14"+
    "\6\0\37\14\1\244\6\14\23\0\2\14\6\0\35\14"+
    "\1\245\10\14\23\0\2\14\6\0\30\14\1\246\15\14"+
    "\23\0\2\14\6\0\12\14\1\247\33\14\23\0\2\14"+
    "\6\0\20\14\1\250\25\14\23\0\2\14\6\0\11\14"+
    "\1\251\34\14\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8060];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\1\11\1\1\2\11\1\1\1\11"+
    "\24\1\1\11\6\1\2\11\1\1\1\11\1\1\1\11"+
    "\1\1\1\11\5\1\2\0\25\1\1\0\11\11\1\0"+
    "\2\1\3\0\31\1\2\0\65\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[169];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
	public String lexeme;
        
        private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }

    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2886) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  @SuppressWarnings("override")
  public Token next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return symbol(sym.INT, new Integer, yytext());
            }
          case 57: break;
          case 2: 
            { return ERROR;
            }
          case 58: break;
          case 3: 
            { return symbol(sym.IDENT, new String(yytext()));
            }
          case 59: break;
          case 4: 
            { return symbol(sym.COMMA);
            }
          case 60: break;
          case 5: 
            { /* ignore */
            }
          case 61: break;
          case 6: 
            { return salto;
            }
          case 62: break;
          case 7: 
            { return symbol(sym.DIVIDE);
            }
          case 63: break;
          case 8: 
            { return symbol(sym.MULTIPLICATION);
            }
          case 64: break;
          case 9: 
            { return symbol(sym.SUM);
            }
          case 65: break;
          case 10: 
            { return symbol(sym.SUBSTRACTION);
            }
          case 66: break;
          case 11: 
            { return symbol(sym.MOD);
            }
          case 67: break;
          case 12: 
            { return symbol(sym.LESS);
            }
          case 68: break;
          case 13: 
            { return symbol(sym.ASSIGN);
            }
          case 69: break;
          case 14: 
            { return symbol(sym.GREATER);
            }
          case 70: break;
          case 15: 
            { return symbol(sym.NOT);
            }
          case 71: break;
          case 16: 
            { return symbol(sym.SEMI_COLON);
            }
          case 72: break;
          case 17: 
            { return symbol(sym.POINT);
            }
          case 73: break;
          case 18: 
            { return symbol(sym.SB_LEFT);
            }
          case 74: break;
          case 19: 
            { return symbol(sym.SB_RIGHT);
            }
          case 75: break;
          case 20: 
            { return symbol(sym.PAR_LEFT);
            }
          case 76: break;
          case 21: 
            { return symbol(sym.PAR_RIGHT);
            }
          case 77: break;
          case 22: 
            { return symbol(sym.BRACKET_LEFT);
            }
          case 78: break;
          case 23: 
            { return symbol(sym.BRACKET_RIGHT);
            }
          case 79: break;
          case 24: 
            { return symbol(sym.CONSTANTE_DOUBLE);
            }
          case 80: break;
          case 25: 
            { return symbol(sym.IF);
            }
          case 81: break;
          case 26: 
            { return symbol(sym.LESS_EQUAL);
            }
          case 82: break;
          case 27: 
            { return symbol(sym.EQUAL);
            }
          case 83: break;
          case 28: 
            { return symbol(sym.GREATER_EQUAL);
            }
          case 84: break;
          case 29: 
            { return symbol(sym.DIFFERENT);
            }
          case 85: break;
          case 30: 
            { return symbol(sym.AND);
            }
          case 86: break;
          case 31: 
            { return symbol(sym.OR);
            }
          case 87: break;
          case 32: 
            { return symbol(sym.SB);
            }
          case 88: break;
          case 33: 
            { return symbol(sym.PAR);
            }
          case 89: break;
          case 34: 
            { return symbol(sym.BRAKET);
            }
          case 90: break;
          case 35: 
            { return symbol(sym.FOR);
            }
          case 91: break;
          case 36: 
            { return symbol(sym.INT);
            }
          case 92: break;
          case 37: 
            { return symbol(sym.NEW);
            }
          case 93: break;
          case 38: 
            { return symbol(sym.STRING);
            }
          case 94: break;
          case 39: 
            { return symbol(sym.BOOL);
            }
          case 95: break;
          case 40: 
            { return symbol(sym.ELSE);
            }
          case 96: break;
          case 41: 
            { return symbol(sym.TRUE);
            }
          case 97: break;
          case 42: 
            { return symbol(sym.THIS);
            }
          case 98: break;
          case 43: 
            { return symbol(sym.VOID);
            }
          case 99: break;
          case 44: 
            { return symbol(sym.NULL);
            }
          case 100: break;
          case 45: 
            { return symbol(sym.BREAK);
            }
          case 101: break;
          case 46: 
            { return symbol(sym.FALSE);
            }
          case 102: break;
          case 47: 
            { return symbol(sym.CLASS);
            }
          case 103: break;
          case 48: 
            { return symbol(sym.WHILE);
            }
          case 104: break;
          case 49: 
            { return symbol(sym.RETURN);
            }
          case 105: break;
          case 50: 
            { return symbol(sym.DOUBLE);
            }
          case 106: break;
          case 51: 
            { return symbol(sym.EXTENDS);
            }
          case 107: break;
          case 52: 
            { return symbol(sym.SETBYTE);
            }
          case 108: break;
          case 53: 
            { return symbol(sym.GETBYTE);
            }
          case 109: break;
          case 54: 
            { return symbol(sym.NEWARRAY);
            }
          case 110: break;
          case 55: 
            { return symbol(sym.INTERFACE);
            }
          case 111: break;
          case 56: 
            { return symbol(sym.IMPLEMENTS);
            }
          case 112: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
